Update

diff --git a/trunk/l4/Makefile b/trunk/l4/Makefile
--- a/trunk/l4/Makefile
+++ b/trunk/l4/Makefile
@@ -848,15 +848,27 @@ help::
 	@echo
 	@echo "Miscellaneous targets:"
 	@echo "  switch_ram_base RAM_BASE=0xaddr"
-	@echo "                   - Switch physical RAM base of build to 'addr'." 
-	@echo "  update           - Update working copy by using SVN." 
-	@echo "  cont             - Continue building after fixing a build error." 
-	@echo "  clean            - Call 'clean' target recursively." 
-	@echo "  cleanfast        - Delete all directories created during build." 
-	@echo "  report           - Print out host configuration information." 
-	@echo "  help             - Print this help text." 
+	@echo "                   - Switch physical RAM base of build to 'addr'."
+	@echo "  update           - Update working copy by using SVN."
+	@echo "  cont             - Continue building after fixing a build error."
+	@echo "  clean            - Call 'clean' target recursively."
+	@echo "  cleanfast        - Delete all directories created during build."
+	@echo "  report           - Print out host configuration information."
+	@echo "  help             - Print this help text."
 	@echo "  test             - Execute unit tests."
 	@echo "  listplatforms    - List available platforms."
 
-test::
-	prove -rv "$(OBJ_BASE)/test/t/$(ARCH)_$(CPU)/$(BUILD_ABI)"
+
+test:
+	$(VERBOSE)taparchive="$(TAPARCHIVE)"; \
+	if [ -n "$${taparchive%%/*}" ]; then \
+	  echo "ERROR: TAPARCHIVE must be an absolute path."; \
+	  exit 1; \
+	fi
+	$(VERBOSE)tmptestdir=$$(mktemp -d); \
+	ln -fs "$(OBJ_BASE)/test/t/$(ARCH)_$(CPU)/$(BUILD_ABI)" \
+	       "$${tmptestdir}/bid-tests"; \
+	(cd $$tmptestdir && \
+	 prove $(if $(TAPARCHIVE),-a $(TAPARCHIVE)) $(if $(VERBOSE),,-v) \
+	       -m -r "bid-tests/$${TESTS#bid-tests/}"); \
+	rm -fr "$$tmptestdir"
